services:
  web:
    # container_name: flask_app
    build: .
    ports:
      - "4000:4000"
    env_file: ./.env
    depends_on:
      - db
  db:
    # container_name: flask_db
    image: postgres
    env_file: ./.env
    expose:
      - 5432